VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

   
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = [  "../cookbooks", "../site-cookbooks" ]
    chef.roles_path = "../roles"
    chef.data_bags_path = "../data_bags"
    recipes = %w{ }
    recipes.each do |recipe|
      chef.add_recipe recipe
    end
    chef.encrypted_data_bag_secret_key_path = '~/.data_bag_keys/spaghettiprogramming.com'
  
    # You may also specify custom JSON attributes:
    chef.json = { 
      "run_list" => [
        "role[spaghettiprogramming]"
      ]
    }
  end
end


